### ISSUE TITLE
Is this project dead

### ISSUE THREAD

**Issue by joshk0** [Dmitry1987/vault-chrome-extension#1]
Hi Dmitry,

This is a pretty interesting project for us because we are considering whether or not to renew with lastpass. We have had a mixed experience with it. In order to seek parity with lastpass, we would be looking for a way to conveniently access secrets from browser. leading to our question, is this project dead? Were you able to get as far as you were hoping to with this extension?

**Comment by Dmitry1987** [comment]
Hi! I never improved the plugin because no one at work used it after hackathon :) ... It is possible to develop a good plugin for hashicorp vault and chrome auto-fill passwords and stuff, but will take a lot of work. So I never proceeded with its development, sorry :) 

There is a bunch of other UIs for vault that were developed:
https://medium.com/@djenriquez/vault-ui-2-361cc66fd2bc
https://github.com/djenriquez/vault-ui
https://github.com/Caiyeon/goldfish

hope it helps

**Comment by espoelstra** [comment]
I think this could also be really interested if it had a "local binary" option similar to https://github.com/gopasspw/gopassbridge where the browser extension talks to a local binary that communicates with the `vault` cli utility.  This could allow authentication of the user simply by them logging in with `vault login` once in their CLI and allow sharing this authorization between their browser and their command line tools.

**Comment by Dmitry1987** [comment]
Yeah, this idea can be developed into a useful plugin for some particular use cases. I don't think the use case is really common, so nobody bothers to develop it for now, because only small amount of people will use it. But thanks for your interest guys 👍  appreciate it.

**Comment by mulbc** [comment]
I would like to continue on this - could you please add a license?

**Comment by Dmitry1987** [comment]
Hi @zeichenanonym ! That extension in its current condition is really bad, it's vanilla JS instead of using some sexy React/Vue.js framework to make it look and feel really polished. 
If you think this might be interesting to some people, lets combine our efforts and make it pretty.  I can start by rewriting the same existing steps in Vuetify.js+Vue (I'll do the server login, list secrets, read+write secrets, list mounts), and you will add any other features that you think are needed for the extension to be useful (for example add the auto-fill in for pages, on click of a secret item). 

What do you think? (P.S. if you're not familiar with Vuetify.js, it's piece of cake, the easiest UI framework ever, took me a single afternoon to learn to use it, it's amazing ❤️ )

and yes, the license.. no idea which one to add, what is the most "all free all opensource" license? I never thought I'll be one day adding a license to my piece of code 💃  I feel useful 🤣

**Comment by Dmitry1987** [comment]
@espoelstra  isn't it a security risk if extension talks to local binary? does chrome web store allow this behavior for a published extension? o_O  if so, it opens the doors to huge amount of possibilities of what can be done with these extensions 😃 I never thought it's possible. We will try to implement what you say, this could be interesting, you mean we'll do a "list current auth tokens" operation in CLI and get the token from there? (then we can read the VAULT_ADDR I guess too? for auto filling the default settings, with ability to override only if user wants to access another vault server)

**Comment by mulbc** [comment]
@Dmitry1987 Please check out this list:
https://choosealicense.com/licenses/

How about you add a MIT license?
You can add a `LICENSE` file right from your browser by clicking on the `Create new file` button. When you name it license --> Github will offer you templates.

Feel free to send me an email (see my profile) to discuss how to continue with this project.

**Comment by Dmitry1987** [comment]
@zeichenanonym I added the MIT license :)

**Comment by Razva** [comment]
Is this "doable"? I'm really looking for a Vault + Chrome/Firefox plugin.

**Comment by Dmitry1987** [comment]
HashiCorp has open sourced the official Vault UI recently https://www.hashicorp.com/resources/vault-oss-ui-introduction  and we started using this at work. It lacks the auto filling feature though, for filling the passwords automatically on web pages.
At the moment I don't plan to work on this plugin :( have no time. Should be relatively easy to hire a JavaScript freelancer though, to develop an addon for official UI that will compliment it by the auto-filling feature. I don't know actually how to do it in Chrome, what this extension was doing is connecting to a vault server API, listing mounts, reading any secret and writing it. That is a list of features :)

**Comment by Dmitry1987** [comment]
this plugin is old and ugly, so if anyone will update it using a pretty UI framework or add new features like the autofilling, I'll happily merge.

**Comment by mulbc** [comment]
@Razva have a look at my fork - I've continued @Dmitry1987 's work

**Comment by Razva** [comment]
@mulbc I gave it a shot, stuck [here](https://github.com/mulbc/vaultPass/issues/13).
